# Generated by Django 2.2.16 on 2020-09-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoalbumapp', '0002_auto_20200909_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_uploaded',
            field=models.DateTimeField(),
        ),
    ]
